### ISSUE TITLE
Improve integration tests on windows to test devonfw.bat properly

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#1073]
We have been facing the following bugs:
* #1066 
* #1043
* #1068
* #1071

All of those are just related to bugs in `devon.bat` and broke the setup of devonfw-ide.
Actually the idea of #157 was to prevent such problems.
As this did not happen, we should use this story, to extend our integration tests on windows to do the following:
* [x] do a full initial setup by executing `setup.bat` on the windows machine. This should have revealed #1068. 
* [x] After the `setup.bat` has completed, we should check for exit code 0 (ERRORLEVEL) and further check the users %PATH% variable from the registry once more to prevent #1071 and #954. Maybe for this test we can read the %PATH% from registry before calling `setup.bat` and after and then ensure that by adding the users scripts directory to the first result should be equal to the second result.
* [x] We should somehow unset the environment variables (maybe by running the entire setup in a "subshell CMD") and then check that according software tools such as "mvn" or "java" are not available. Then we call `devon.bat` command and expect that now these tools are available. This should prevent #1066.
* [x] Also during the latter test, we can check from some environment variable from devon.properties not to be present before calling `devon.bat` and then to be present after calling it. This should prevent #1043

Besides this story, we have to do the following checks in every daily meeting:
* are all nightly tests green? if not define who is analyzing the problem on the same day and also reschedule a release if it was planned for that day (releases should then always prepared one day and only be performed the day after if the nightly tests are green).
* are there new (bug) issues in our issue-tracker (https://github.com/devonfw/ide/issues?q=is%3Aopen+is%3Aissue+label%3Abug)? If so, let us have a look with the entire team.

**Comment by maybeec** [comment]
I feel you could easily reuse what is already implemented in the tutorial compiler and set it up within the devonfw ide repository:

test spec: https://github.com/devonfw-tutorials/tutorials/blob/main/devonfw-ide/index.asciidoc
workflow spec: https://github.com/devonfw-tutorials/tutorials/blob/main/.github/workflows/buildMain.yml
recent execution: https://github.com/devonfw-tutorials/tutorials/actions/runs/4419868086/jobs/7748856469
run-command: https://github.com/devonfw-tutorials/tutorial-compiler/blob/main/runners/console/index.ts#L45
assertion: https://github.com/devonfw-tutorials/tutorial-compiler/blob/main/runners/console/index.ts#L547

**Comment by maybeec** [comment]
Even more easier would be possibly to copy out run command and assertion code and execute it directly with nodejs.

**Comment by hohwille** [comment]
@maybeec thanks for your hints and suggestion. The problem is that we want to do a test of devonfw-ide that has just been build before it can be published anywhere while the solution you linked downloads devonfw-ide for maven central.
IMHO this does not fit together.
Actually we already have solved all the problems of test-infrastructure for devonfw-ide so we can extract the build package and run tests on it. The problem is more that the tests themselves are not covering important cases. Whether we do that in bash or node IMHO does not make any different value.
However, from your runs we have seen that you managed to get colored output even from github action logs. We could not yet get this to work and we will dig into your solution to make this happen so the output will become much more readable.

**Comment by alfeilex** [comment]
I found the reason why the setup.bat were not executed while `test-setup`. 
https://github.com/devonfw/ide/blob/5e55ff4e4fee1e35377b00e568b6d46314f2f1ab/scripts/pom.xml#L156-L160

Our tests are run by `mvn-exec-plugin` and use bash shell. So if we run `mvn clean install` the current `all-tests` script would throw errors. For example this asterix
