### ISSUE TITLE
3rd party license clarification

### ISSUE THREAD

**Issue by hohwille** [devonfw/ide#291]
For legal clarification, we need to reference all licenses including their version so that our terms of use are clear and leave no ambiguity.
https://github.com/devonfw/ide/blob/master/TERMS_OF_USE.asciidoc

Open issues:
* [x] [Spotbugs](https://marketplace.eclipse.org/content/spotbugs-eclipse-plugin): LGPL? Which version? Where is the source-code? Is there a github repo?
* [x] [tm-terminal](https://marketplace.eclipse.org/content/tm-terminal): EPL? Which version? Where is the source-code? The link there leads to a page with `No repositories found`.
* [x] ~~[Dev-Style](https://www.genuitec.com/products/devstyle/): Is there also a license for the code? Is this OSS at all?~~ Kicked out
* [x] [regex tester](http://myregexp.com/eclipsePlugin.html) is flagged as GPL without version. Seems 2.0: see [here](https://sourceforge.net/projects/regex-util/)
* [x] New: cicdgen has to be included after PR #292 
* [x] New: devon4node has to be included after PR #292 
* [x] New: SonarQube has to be included after PR #289
* [x] New: Jenkins has to be included due to PR #102

If there is nothing more to find on the web-sites, we need to contact the project maintaines. Emails or links for that should be available for all the projects above to clarify.

**Comment by dhelmke** [comment]
> Spotbugs: LGPL? Which version? Where is the source-code? Is there a github repo?

I think Spotbugs has the :

GNU LESSER GENERAL PUBLIC LICENSE
Version 2.1, February 1999
https://github.com/spotbugs/spotbugs/blob/master/spotbugs/licenses/LICENSE.txt

Here is the source code on the github repo:

https://github.com/spotbugs/spotbugs



> tm-terminal: EPL? Which version? Where is the source-code?


I think this is the source code:
https://git.eclipse.org/c/tm/org.eclipse.tm.git/tree/terminal

In the repo in a file I found this license:

Eclipse Public License 2.0
https://git.eclipse.org/c/tm/org.eclipse.tm.git/tree/terminal/plugins/org.eclipse.tm.terminal.view.ui/about.html


> Dev-Style: Is there also a license for the code? Is this OSS at all?

On this website it says it is absolutely  free:
https://www.genuitec.com/products/devstyle/

Here they say it is:
Commercial – Free
https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle

**Comment by dhelmke** [comment]
I wrote an email to the company from DevStyle. They answered me:

1) No, it is not OSS.
2) Here is our license: https://www.genuitec.com/products/devstyle/eula/

**Comment by hohwille** [comment]
@dhelmke thanks for taking this over and clarifying all the things while I was away. 👍 You really helped me a lot with that.

**Comment by hohwille** [comment]
As DevStyle is not OSS and has a complex EULA it currently blocks our official public release.
I am very sorry about this, but I will have to remove it. Same already happened for ObjectAID, Still I will try to clarify legal implications and if possible bring it back. However, for the moment it is better to have a release without it but not to have any release... You know IANAL but I have to care what they say... Yes, sucks and free and/or OSS and Licenses should actually help to make the world better but sometimes things are just complicated...

**Comment by hohwille** [comment]
I will close this issue. The clarification of the text of the TERMS_OF_USE is still ongoing. Will create a separate issue if needed, but everything else is now done.
